### ISSUE TITLE
No data for count more than 126

### ISSUE THREAD

**Issue by naveen26246** [tyrrellsytems/node-red-contrib-serial-modbus#23]
Hi, 

When Im trying to read holding registers at a particular address with a count more than 126, the node does not send any data. I am fairly new to modbus. Is there a way to read larger counts with a single node ? 

Thanks,
Naveen

**Comment by hardillb** [comment]
I would suggest you use [node-red-contrib-modbus](https://flows.nodered.org/node/node-red-contrib-modbus) as this node is no longer really being actively maintained
